name: Build
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "@felixcolaci/auth0-progressive-profiling-action"
          token: ${{ secrets.WRITE_REPO }}
